### ISSUE TITLE
Question: is it possible to use one connection on multiple pages?

### ISSUE THREAD

**Issue by anatoliy-t7** [razshare/sveltekit-sse#61]
Is it possible to use one connection on multiple pages?

I mean, I have one connection and when I go to other page keep it, without make new one ?

**Comment by razshare** [comment]
Hello @anatoliy-t7 
Yes it is possible.

Declare your `source()` object in an external file, for example `src/lib/sources.js`

```js
import { source } from 'sveltekit-sse'
export const connection = source('/custom-event')
```

You don't have to worry about shared state on the server, the `source()` function always returns a store initialized with a blank value while rendering on the server.

When your client-side router takes over your application, the connection is created as you import the property `connection` from your `src/lib/sources.js` module.

That means you can treat it as any other store and you can share it across pages and components.

However, as any store, whenever all subscribers unsubscribe, the store becomes inactive.\
In this case, it means that the connection is destroyed.\
I designed it this way to avoid creating dangling connections all over the place.\
If you want connections to persist across page transitions you have to make sure there's at least 1 subscriber watching the stream at all times.

So you would need to add a subscriber, perhaps in your module, like so:

```js
import { source } from 'sveltekit-sse'
export const connection = source('/events')
connection.select('message').subscribe(function watcher(value){
  console.log(value)
})
```

This will make sure there's always at least 1 subscriber watching the store and prevent it from closing automatically.

Let me know if this fixes your issue.

**Comment by anatoliy-t7** [comment]
Thank you for the answer.
I want to show what I did now
``` js
// my global +layout.svelte
	import App from '$lib/state/app.svelte';
	import { source } from 'sveltekit-sse';

	let { children } = $props();

	const connection = source('/api/notifier', {
		close({ connect }) {
			// connect();
		},
		error({ error }) {
			console.error('subscribe', error);
		}
	});

       // global store
	App.message = connection.select('notify').transform(function run(data: string) {
		return JSON.parse(data);
	});
```

``` js
// some page
	import App from '$lib/state/app.svelte';
	let message = $derived(App.message);

	watch(
		() => $message?.record,
		() => {
			if ($message?.model === 'notification') {
			     //My logic here
			}
		}
	);
```
It works locally but doesn't work on a server.

**Comment by razshare** [comment]
Hello again @anatoliy-t7 , if you want me to take a look at your code please provide a reproduction repository that isolates your specific issue.

This way it's easier to deal with code and maybe even find out bugs.

I'm usually most active on Saturdays and Sundays in this repository, but I might be able to take a look at your reproduction during the week as well.

**Comment by anatoliy-t7** [comment]
Actually, It is working perfectly locally, but it doesn't work on a server via Nginx.

My current nginx settings:
```
location /api/notifier {
        proxy_pass http://dev/api/notifier;
        proxy_http_version 1.1;

        proxy_set_header Origin http://$http_host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_set_header Connection '';
        proxy_set_header X-Accel-Buffering no;

        proxy_buffers 4 256k;
        proxy_buffer_size 128k; 
        proxy_busy_buffers_size 256k;
        proxy_ssl_server_name on;
        proxy_buffering off;
        proxy_cache off;

        proxy_cache_bypass $http_upgrade;
        chunked_transfer_encoding off;
    }
    ```

**Comment by anatoliy-t7** [comment]
In the end, it was Bun who gave trouble.
